# Generated by Django 3.1.2 on 2020-10-23 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointmentrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentRequest',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time1',
        ),
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.CharField(default=0, max_length=3, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='confirm_appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 10, 54, 15, 196267, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.CharField(default='', max_length=30, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Patient Name'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 23, 10, 54, 15, 196290, tzinfo=utc), verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default=0, max_length=3, verbose_name='Age'),
        ),
    ]
