# Generated by Django 3.1.2 on 2020-10-23 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20201023_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 11, 16, 0, 941674, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 23, 11, 16, 0, 941695, tzinfo=utc), verbose_name='Time'),
        ),
    ]
