# Generated by Django 2.1.4 on 2020-10-23 15:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20201023_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital', models.CharField(max_length=100)),
                ('Beds_Cap', models.IntegerField()),
                ('Beds_occ', models.IntegerField()),
                ('Max_Vent', models.IntegerField()),
                ('Active_vent', models.IntegerField()),
                ('Active_Covid', models.IntegerField()),
                ('Max_ICU', models.IntegerField()),
                ('Active_ICU', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 15, 50, 13, 989405, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.datetime(2020, 10, 23, 15, 50, 13, 989405, tzinfo=utc), verbose_name='Time'),
        ),
    ]
