# Generated by Django 3.1.2 on 2020-10-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add',
            new_name='Data',
        ),
    ]
